<?php

use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;

Route::get('/', [AdminController::class, 'index']);
Route::get('/login', [AdminController::class, 'loginPage']);
Route::get('/dashboard', [AdminController::class, 'dashboard']);
Route::get('/nodes', [AdminController::class, 'nodes']);
Route::get('/plans', [AdminController::class, 'plans']);
Route::get('/enroll', [AdminController::class, 'enroll']);
Route::get('/users', [AdminController::class, 'users']);
Route::get('/subscriptions', [AdminController::class, 'subscriptions']);
Route::get('/grants', [AdminController::class, 'grants']);
Route::get('/devices', [AdminController::class, 'devices']);
Route::get('/traffic', [AdminController::class, 'traffic']);
Route::get('/traffic/live', [AdminController::class, 'trafficLive']);
Route::get('/traffic/health', [AdminController::class, 'trafficHealth']);
Route::post('/assistant/message', [AdminController::class, 'assistantMessage']);
Route::post('/assistant/confirm', [AdminController::class, 'assistantConfirm']);
Route::get('/audit', [AdminController::class, 'audit']);
Route::post('/login', [AdminController::class, 'login']);
Route::post('/logout', [AdminController::class, 'logout']);
Route::post('/nodes/enroll', [AdminController::class, 'enrollNode']);
Route::post('/grants/{grantId}/revoke', [AdminController::class, 'revokeGrant']);
Route::post('/subscriptions/{subscriptionId}/status', [AdminController::class, 'updateSubscriptionStatus']);
Route::post('/subscriptions', [AdminController::class, 'createSubscription']);
Route::post('/subscriptions/manual', [AdminController::class, 'createManualSubscription']);
Route::post('/subscriptions/{subscriptionId}/edit', [AdminController::class, 'editSubscription']);
Route::post('/subscriptions/{subscriptionId}/reset-usage', [AdminController::class, 'resetSubscriptionUsage']);
Route::post('/subscriptions/{subscriptionId}/reissue', [AdminController::class, 'reissueSubscription']);
Route::post('/subscriptions/{subscriptionId}/delete', [AdminController::class, 'deleteSubscription']);
Route::post('/users/{userId}/role', [AdminController::class, 'updateUserRole']);
Route::post('/users', [AdminController::class, 'createUser']);
Route::post('/users/{userId}', [AdminController::class, 'updateUser']);
Route::post('/users/{userId}/disable', [AdminController::class, 'disableUser']);
Route::post('/users/{userId}/enable', [AdminController::class, 'enableUser']);
Route::post('/users/{userId}/delete', [AdminController::class, 'deleteUser']);
Route::post('/plans', [AdminController::class, 'createPlan']);
Route::post('/plans/{planId}', [AdminController::class, 'updatePlan']);
Route::post('/plans/{planId}/delete', [AdminController::class, 'deletePlan']);
Route::post('/devices/{deviceId}/revoke', [AdminController::class, 'revokeDevice']);
